
//login user 
###

POST  http://localhost:3000/users/
Content-Type: application/json

{
    "username" : "somesh124",
    "name" : "somesh",
    "password" : "somesh@123",
    "gender" : "male",
    "location" : "chennai"
}

###
POST http://localhost:3000/login/
Content-Type: application/json

{
    "username" :"somesh12",
    "password" :"somesh@123"
}

